#!/usr/bin/env node
/**
 * Minimal static file server for the knx2home `out/` directory.
 * Serves the Next.js static export generated by `npm run build`.
 *
 * Serves HTTPS when a TLS keypair is present in ./certs (see the Docker
 * entrypoint, which generates a self-signed cert when none is provided).
 * A HTTPS connection is a secure context, so crypto.subtle (Web Crypto)
 * is available even with a self-signed certificate.
 */
const http = require("http");
const https = require("https");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "out");
const certDir = path.join(__dirname, "certs");
const hasTls =
  fs.existsSync(path.join(certDir, "server.crt")) &&
  fs.existsSync(path.join(certDir, "server.key"));
const port = Number(process.env.PORT || 3000);
const types = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript",
  ".mjs": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".gif": "image/gif",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".txt": "text/plain",
};

const requestHandler = (req, res) => {
  let urlPath = decodeURIComponent(new URL(req.url, "http://localhost").pathname || "/");
  if (urlPath === "/") urlPath = "/index.html";
  let filePath = path.normalize(path.join(root, urlPath));
  // Prevent path traversal outside the served root.
  if (!filePath.startsWith(root)) {
    res.writeHead(403, { "Content-Type": "text/plain" });
    res.end("403 Forbidden");
    return;
  }
  fs.stat(filePath, (err, stat) => {
    if (err) {
      res.writeHead(404, { "Content-Type": "text/plain" });
      res.end("404 Not Found");
      return;
    }
    if (stat.isDirectory()) {
      // Next static export: `/tool` is served by `out/tool.html` and the
      // directory `out/tool/` holds only `_next` data files.
      const candidates = [
        filePath + ".html",
        path.join(filePath, "index.html"),
      ];
      filePath = candidates.find((c) => fs.existsSync(c));
      if (!filePath) {
        res.writeHead(404, { "Content-Type": "text/plain" });
        res.end("404 Not Found");
        return;
      }
    }
    res.writeHead(200, {
      "Content-Type": types[path.extname(filePath)] || "application/octet-stream",
      "Cache-Control": "no-cache",
    });
    fs.createReadStream(filePath).pipe(res);
  });
};

const server = hasTls
  ? https.createServer(
      {
        cert: fs.readFileSync(path.join(certDir, "server.crt"), "utf8"),
        key: fs.readFileSync(path.join(certDir, "server.key"), "utf8"),
      },
      requestHandler
    )
  : http.createServer(requestHandler);

server.listen(port, () => {
  const scheme = hasTls ? "https" : "http";
  console.log(`knx2home serving ${root} on ${scheme}://localhost:${port}`);
});
